/*
 * This file contains course and lab specific parameters for drivers.
 * It was generated by genhdrs.pl. Do not modify it.
 */
#define LAB "malloclab"
#define SERVER_NAME ""
#define SERVER_PORT 80
#define COURSE_NAME "cs24"
#define AUTOGRADE_TIMEOUT 360
